name: desi_fitness
description: "A Desi Fitness and Diet App with iOS Style UI."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # iOS Style Icons
  cupertino_icons: ^1.0.8

  # Firebase Dependencies (Authentication & Core)
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  # Agar fitness app me user ka data (jaise diet plan ya workout) save karna hai, 
  # toh firestore add karna padega:
  cloud_firestore: ^4.13.6 

  # Extra Tools (Agar app me PDF ya images download karwani hain tabhi inko rakhein)
  path_provider: ^2.1.2
  dio: ^5.4.0
  ffi: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
