name: desi_fitness
description: "A Desi Fitness and Diet App with iOS Style UI."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Firebase Dependencies (Aapke Desi Fitness wale)
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3

  # Pro IDE / Offline Builder Dependencies (Jo errors fix karenge)
  path_provider: ^2.1.2
  dio: ^5.4.0
  ffi: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
